# Generated by Django 5.2.17 on 2026-10-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_cooking_time_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, verbose_name='Temps de préparation (minutes)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_url',
            field=models.URLField(blank=True, default='', verbose_name='URL de la recette'),
        ),
    ]
